feat: #25 добавить ЧПУ + эндпоинт /homepage для загрузки товаров на главной + настроить миграции

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -26,8 +26,20 @@ jobs:
             git fetch origin
             git checkout master
             git reset --hard origin/master
+          
             cd deploy
             sudo docker-compose down
             sudo docker-compose up -d --build
             echo "Docker Compose deployment completed."
+          
+            # Run DB migrations
+            echo "Running database migrations..."
+            if ! sudo docker exec -t backend sh -c 'migrate -path ./infrastructure/db/migrations -database "$DATABASE_URL" up'; then
+              echo "ERROR: Database migrations failed. Aborting deployment."
+              exit 1
+            fi
+          
+            # Fill slugs
+            echo "Filling slugs..."
+            sudo docker exec -t backend sh -c 'cd /build && ./fill_slugs'
           EOF
